# This is a basic workflow to build and deploy a docker contaioner

name: DockerBuild

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      APP_NAME: sample-spring-boot-application

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # set a short sha to use as tag
      - name: Add dynamic envs
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      -
        name: checkout
        uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: registry.devopsnow.io
          username: ${{ secrets.SANDBOX_DOCKER_REPO_USERNAME }}
          password: ${{ secrets.SANDBOX_DOCKER_REPO_PASSWORD }}
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./server
          tags: "registry.devopsnow.io/public-sandbox/${{ github.repository }}/${{ env.APP_NAME }}:${{ env.SHORT_SHA }}"
      - run: docker push "registry.devopsnow.io/public-sandbox/${{ github.repository }}/${{ env.APP_NAME }}:${{ env.SHORT_SHA }}"
